#ifndef RPG_DEFINITIONS_HPP
#define RPG_DEFINITIONS_HPP

#define YELLOWDEBUG 2
#define PROJECT_NAME RPG
#define PROJECT_VERSION 0

#define PICSIZE 32
#define HIGHT 20
#define WIDTH 35
#define SCREENHIGHT HIGHT*PICSIZE
#define SCREENWIDTH WIDTH*PICSIZE



#endif
